Product.destroy_all

Product.create!([
  {name: "Refrigerator", price: 58, image_url: "https://loremflickr.com/300/300/appliance", description: "Ut et quis. Odit iste occaecati. Fugit aliquam aspernatur. Debitis repellendus ipsum. Rerum quia quisquam. Ut expedita doloribus.", inventory: 5, supplier_id: 1},
  {name: "HVAC", price: 44, image_url: "https://loremflickr.com/300/300/appliance", description: "Dolores repellat et. Ad doloribus excepturi. Omnis ut sint. Deserunt vel est. Sit non nostrum. Aspernatur consequatur eos.", inventory: 5, supplier_id: 1},
  {name: "Drawer dishwasher", price: 93, image_url: "https://loremflickr.com/300/300/appliance", description: "Est qui aut. Non at minus. Similique dolor iste. Suscipit ut delectus. Modi inventore aut. Aut voluptates et.", inventory: 5, supplier_id: 1},
  {name: "Sewing machine", price: 58, image_url: "https://loremflickr.com/300/300/appliance", description: "Suscipit et nostrum. Cupiditate qui quasi. Ut eius ad. Nisi facere molestiae. Amet molestias numquam. Qui nostrum architecto.", inventory: 5, supplier_id: 1},
  {name: "Dishwasher", price: 73, image_url: "https://loremflickr.com/300/300/appliance", description: "Odio quae animi. Dolores eaque consequatur. Nostrum et omnis. Qui iste repellat. Minus qui facilis. Sapiente accusantium odit.", inventory: 5, supplier_id: 1},
  {name: "Flame supervision device", price: 74, image_url: "https://loremflickr.com/300/300/appliance", description: "Sapiente earum totam. Accusamus aut omnis. Dignissimos eaque placeat. Nihil modi non. Ducimus non quisquam. Tempore laborum impedit.", inventory: 5, supplier_id: 1},
  {name: "Back boiler", price: 31, image_url: "https://loremflickr.com/300/300/appliance", description: "Aspernatur deserunt et. Qui qui perspiciatis. Natus suscipit officiis. Non et aut. In id rerum. Officia nam et.", inventory: 5, supplier_id: 1},
  {name: "Kimchi refrigerator", price: 35, image_url: "https://loremflickr.com/300/300/appliance", description: "Dolorem qui voluptatum. Odit iure aperiam. Consequatur earum unde. In nam at. Debitis beatae velit. Commodi dignissimos aut.", inventory: 5, supplier_id: 1},
  {name: "Flame supervision device", price: 78, image_url: "https://loremflickr.com/300/300/appliance", description: "Quo sunt aut. Voluptas sunt atque. Nemo est nisi. Excepturi quia qui. Veritatis architecto blanditiis. Sunt rerum quisquam.", inventory: 5, supplier_id: 1},
  {name: "Air ioniser", price: 73, image_url: "https://loremflickr.com/300/300/appliance", description: "Aliquam illum soluta. Fugit tempore tempora. Aut expedita minus. Sequi aspernatur et. Placeat dolorum dolorem. Deserunt reiciendis eveniet.", inventory: 5, supplier_id: 1},
  {name: "Trouser press", price: 21, image_url: "https://loremflickr.com/300/300/appliance", description: "Aut aperiam ut. Inventore qui voluptatem. Aliquid praesentium ratione. Id recusandae vitae. Et officia voluptate. Rerum unde voluptatem.", inventory: 5, supplier_id: 1},
  {name: "Oven", price: 89, image_url: "https://loremflickr.com/300/300/appliance", description: "Dolor ut sed. Modi quo mollitia. Voluptas aperiam reprehenderit. Et reiciendis cumque. Accusamus excepturi fugit. Ut cupiditate aut.", inventory: 5, supplier_id: 1},
  {name: "Domestic robot", price: 39, image_url: "https://loremflickr.com/300/300/appliance", description: "Est ex deleniti. Cum aut et. Doloribus optio voluptas. Vero sequi impedit. Modi iure quidem. Inventore dolores ad.", inventory: 5, supplier_id: 1},
  {name: "Paper shredder", price: 54, image_url: "https://loremflickr.com/300/300/appliance", description: "Est accusamus ut. Quis ipsam qui. Totam ab illum. Accusantium sequi in. Quidem voluptatum sed. Voluptatem et quaerat.", inventory: 5, supplier_id: 1},
  {name: "Bed", price: 899, image_url: "picture.com", description: "A comfy place to sleep", inventory: 5, supplier_id: 1},
  {name: "Bed", price: 899, image_url: "picture.com", description: "A comfy place to sleep", inventory: 5, supplier_id: 1},
  {name: "Exhaust hood", price: 70, image_url: "https://loremflickr.com/300/300/appliance", description: "Necessitatibus eius exercitationem. Qui earum debitis. Perferendis aperiam nihil. Ab molestias cupiditate. Molestiae ex qui. Odio quis perspiciatis.", inventory: 5, supplier_id: 1},
  {name: "Oven", price: 799, image_url: "image.com", description: "Brand new, never used, black, self-cleaning", inventory: 5, supplier_id: 1}
])
